import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/AuthContext';
import MobileSidebar from '@/components/layout/MobileSidebar';
import Sidebar from '@/components/layout/Sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`}
        >
          <div className="flex min-h-screen">
            {/* デスクトップ用サイドバー */}
            <aside className="hidden md:block fixed inset-y-0 left-0 z-20">
              <Sidebar />
            </aside>
            {/* モバイル用サイドバー（ハンバーガー） */}
            {/* モバイル用サイドバー（ハンバーガーメニュー＋ドロワー） */}
            <div className="md:hidden fixed top-0 left-0 w-full bg-white border-b shadow z-30 flex items-center justify-between px-4 py-2">
              <MobileSidebar />
              <span className="font-bold text-lg">AI円卓会議</span>
            </div>
            {/* メインコンテンツ */}
            <main className="flex-1 ml-0 md:ml-64">{children}</main>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
